# Generated by Django 5.0.6 on 2024-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='crefito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='especialidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
