# Generated by Django 5.0.6 on 2024-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_crefito_cliente_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=None, max_length=14, null=True),
        ),
    ]
