# Generated by Django 5.0.6 on 2024-06-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_cliente_crefito_remove_cliente_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisio', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
    ]
