# Generated by Django 5.0.6 on 2024-06-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='fisio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.profissional'),
        ),
    ]
