# Generated by Django 5.0.6 on 2024-06-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_consulta_especialidade_remove_consulta_fisio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
