# Generated by Django 5.0.6 on 2024-06-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_consulta_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('concluido', 'Concluído')], default='em aberto', max_length=20),
        ),
    ]
