# Generated by Django 5.0.6 on 2024-06-22 00:08

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_consulta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clients.models.user_directory_path),
        ),
    ]
