# Generated by Django 5.0.6 on 2024-06-22 02:53

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_cliente_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clients.models.user_directory_path),
        ),
    ]
