# Generated by Django 5.0.6 on 2024-06-22 03:11

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_profissional_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clients.models.prof_directory_path),
        ),
    ]
