# Generated by Django 5.0.6 on 2024-06-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_profissional_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.profissional')),
            ],
        ),
    ]
