# Generated by Django 5.0.6 on 2024-06-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='horario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_final',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_inicial',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
    ]
