# Generated by Django 5.0.6 on 2024-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_consulta_horario_consulta_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario_inicial',
            field=models.TimeField(),
        ),
    ]
